version: 0.1


phases:
  install:
    commands:
      - 
  pre_build:
    commands:
      - echo Logging in to Amazon ECR.
      - $(aws ecr get-login --region $AWS_REGION --no-include-email)
  build:
    commands:
      - echo listing files
      - ls -lart
      - echo Building the Docker image...
      - docker build -t $REPO_URI:latest .
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Pushing image
      - docker push $REPO_URI:latest
      - printf '[{"name":"flask-webapp-c","imageUri":"%s"}]' $REPO_URI:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
