version: 0.1

phases:
  install:
    commands:
      - 
  pre_build:
    commands:
      - echo Logging in to Amazon ECR.
      - AWS_REGION=eu-west-1
      - $(aws ecr get-login --region $AWS_REGION --no-include-email)
      - IMAGE_NAME=flask-webapp
      - REPO_URI=426132435523.dkr.ecr.eu-west-1.amazonaws.com/ecs-alb-with-flask/home
      - IMAGE_TAG=latest
  build:
    commands:
      - echo listing files
      - ls -lart
      - echo Building the Docker image...
      - docker build --help
      - echo $IMAGE_NAME
      - echo $IMAGE_TAG
      - docker build -t $REPOSITORY_URI:$(date +%Y%m%d)-$IMAGE_TAG .
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Pushing image
      - docker push $REPOSITORY_URI:$(date +%Y%m%d)-$IMAGE_TAG
