version: 0.1


phases:
  install:
    commands:
      - 
  pre_build:
    commands:
      - echo Logging in to Amazon ECR.
      - AWS_REGION=eu-west-1
      - $(aws ecr get-login --region $AWS_REGION --no-include-email)
  build:
    commands:
      - echo listing files
      - ls -lart
      - echo Building the Docker image...
      - docker build -t 426132435523.dkr.ecr.eu-west-1.amazonaws.com/ecs-alb-with-flask/home:latest .
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Pushing image
      - docker push 426132435523.dkr.ecr.eu-west-1.amazonaws.com/ecs-alb-with-flask/home:latest
      - printf '[{"name":"flask-webapp-c","imageUri":"%s"}]' 426132435523.dkr.ecr.eu-west-1.amazonaws.com:$(date +%Y%m%d)-latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
